version: "1"
    rules:
      - base: bdw-dev
        upstream: develop
        mergeMethod: merge
        assignees:
          - skulegirl
      - base: develop
        upstream: Fantomas42:develop
        mergeMethod: hardreset
        mergeUnstable: true
        conflictReviewers:
          - skulegirl
